# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Function

on:
  push:
    paths:
      - '*'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '*.md'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3
      - name: Install dependency for function
        run: pip install -r requirements.txt
      - name: Test function
        run: chmod u+x job.sh
      - run: ./job.sh
